apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: apps
spec:
  components:
  - name: apps
    type: kustomize
    properties:
      repoType: git
      url: https://github.com/aaditya09/petclinic-app
      pullInterval: 5m
      git:
        branch: master
      path: ./apps
