apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: petclinic-app
  namespace: default
spec:
  components:
    - name: petclinic-backend
      type: webservice
      properties:
        image: aadi007/petclinic:1.0-SNAPSHOT
        port: 8080
        env:
          - name: DB_HOST
            value: mysql-cluster-mysql.default.svc.cluster.local:3306
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: ROOT_PASSWORD
      traits:
        - type: ingress
          properties:
            domain: testyopetclinic.example.com
            http:
              /: 8080
