apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: petclinic-app
  namespace: default
spec:
  components:
    - name: petclinic-backend
      type: webservice
      properties:
        image: aadi007/petclinic:1.0-SNAPSHOT
        port: 8080
      traits:
        - type: ingress
          properties:
            domain: localhost
            http:
              /: 8080
